name: Auto Release

on:
  push:
    branches: [ main ]
    paths:
      - 'pyproject.toml'

permissions:
  contents: write
  id-token: write

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version-changed: ${{ steps.check.outputs.version-changed }}
      new-version: ${{ steps.check.outputs.new-version }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 2
        
    - name: Check if version changed
      id: check
      run: |
        # Get current version from pyproject.toml
        CURRENT_VERSION=$(grep '^version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
        echo "Current version: $CURRENT_VERSION"
        
        # Get previous version from pyproject.toml
        git checkout HEAD~1 -- pyproject.toml 2>/dev/null || echo "No previous version"
        PREVIOUS_VERSION=$(grep '^version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/' 2>/dev/null || echo "none")
        echo "Previous version: $PREVIOUS_VERSION"
        
        # Restore current pyproject.toml
        git checkout HEAD -- pyproject.toml
        
        if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ] && [ "$PREVIOUS_VERSION" != "none" ]; then
          echo "version-changed=true" >> $GITHUB_OUTPUT
          echo "new-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
        else
          echo "version-changed=false" >> $GITHUB_OUTPUT
          echo "Version unchanged"
        fi

  release:
    needs: check-version
    if: needs.check-version.outputs.version-changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
        
    - name: Install dependencies
      run: poetry install --no-interaction --with dev
      
    - name: Run full test suite
      run: |
        poetry run pytest tests/test_linting.py -v
        poetry run pytest tests/test_test.py -v -m "not integration" --cov=cmdrnafold --cov-fail-under=90
        
    - name: Run security scan
      run: poetry run bandit -r src/ -ll
      
    - name: Build package
      run: poetry build
      
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ needs.check-version.outputs.new-version }}
        release_name: Release v${{ needs.check-version.outputs.new-version }}
        body: |
          ## Changes in v${{ needs.check-version.outputs.new-version }}
          
          This release was automatically created when the version was updated in pyproject.toml.
          
          ### Installation
          ```bash
          pip install cmdrnafold==${{ needs.check-version.outputs.new-version }}
          ```
          
          ### What's Changed
          - Version bump to ${{ needs.check-version.outputs.new-version }}
          - All tests passing
          - Security scan completed
          
          **Full Changelog**: https://github.com/${{ github.repository }}/commits/v${{ needs.check-version.outputs.new-version }}
        draft: false
        prerelease: false
        
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/cmdrnafold-${{ needs.check-version.outputs.new-version }}-py3-none-any.whl
        asset_name: cmdrnafold-${{ needs.check-version.outputs.new-version }}-py3-none-any.whl
        asset_content_type: application/zip
        
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
